//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptGen.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aaron
        ///Abraham
        ///Adam
        ///Adrian
        ///Aidan
        ///Alan
        ///Albert
        ///Alejandro
        ///Alex
        ///Alexander
        ///Alfred
        ///Andrew
        ///Angel
        ///Anthony
        ///Antonio
        ///Ashton
        ///Austin
        ///Aaliyah
        ///Abigail
        ///Ada
        ///Adelina
        ///Agatha
        ///Alexa
        ///Alexandra
        ///Alexis
        ///Alise
        ///Allison
        ///Alyssa
        ///Amanda
        ///Amber
        ///Amelia
        ///Angelina
        ///Anita
        ///Ann
        ///Ariana
        ///Arianna
        ///Ashley
        ///Audrey
        ///Autumn
        ///Ava
        ///Avery
        ///Benjamin
        ///Bernard
        ///Blake
        ///Brandon
        ///Brian
        ///Bruce
        ///Bryan
        ///Bailey
        ///Barbara
        ///Beatrice
        ///Belinda
        ///Brianna
        ///Bridjet
        ///Brooke
        ///Cameron
        ///Carl
        ///Carlos
        ///Charles
        ///Christopher
        ///Cole
        ///Connor
        ///Caleb
        ///Cart [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Name {
            get {
                return ResourceManager.GetString("EN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adams
        ///Aldridge
        ///Alexander
        ///Alison
        ///Allison
        ///Alix
        ///Allen
        ///Anderson
        ///Bailey
        ///Baker
        ///Barber
        ///Barlow
        ///Barrett
        ///Bee
        ///Bell
        ///Bennett
        ///Benson
        ///Bentley
        ///Beverly
        ///Black
        ///Bradley
        ///Brett
        ///Bronte
        ///Brooke
        ///Brooks
        ///Brown
        ///Bruce
        ///Burgess
        ///Burney
        ///Burns
        ///Byrne
        ///Campbell
        ///Carr
        ///Carson
        ///Carter
        ///Clark
        ///Cole
        ///Collins
        ///Cooper
        ///Cox
        ///Crawford
        ///Crystal
        ///Davis
        ///Day
        ///Dean
        ///Dee
        ///Eden
        ///Edwards
        ///Ellis
        ///Evans
        ///Farrell
        ///Fisher
        ///Florence
        ///Ford
        ///Foster
        ///Franklin
        ///George
        ///Gibson
        ///Gordon
        ///Graham
        ///Grant
        ///Green
        ///Haley
        ///Hall
        ///Harris
        ///Hart
        ///Hick [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Surname {
            get {
                return ResourceManager.GetString("EN_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a
        ///abandon
        ///abandoned
        ///abate
        ///abbey
        ///abbreviation
        ///ABC
        ///abide
        ///ability
        ///able
        ///aboard
        ///abode
        ///abominable
        ///about
        ///above
        ///abroad
        ///abrupt
        ///abruptly
        ///absence
        ///absent
        ///absolute
        ///absolutely
        ///absorb
        ///absorbed
        ///absorption
        ///abstract
        ///absurd
        ///absurdity
        ///abundance
        ///abundant
        ///acacia
        ///accent
        ///accept
        ///accepted
        ///access
        ///accessible
        ///accident
        ///accidental
        ///accidentally
        ///acclaim
        ///accommodate
        ///accommodation
        ///accompany
        ///accompanying
        ///accomplice
        ///accomplish
        ///accomplished
        ///accord
        ///accordance
        ///according
        ///accordingly
        ///account
        ///accou [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Word {
            get {
                return ResourceManager.GetString("EN_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авдокея
        ///Авдоким
        ///Авдоня
        ///Авдотька
        ///Авдотьюшка
        ///Авдотья
        ///Авдоха
        ///Авдоша
        ///Авдуля
        ///Авдуся
        ///Аграфена
        ///Аграфенка
        ///Агрипинка
        ///Агрипка
        ///Агриппа
        ///Агриппина
        ///Агриппич
        ///Агриппична
        ///Ада
        ///Адам
        ///Адамушка
        ///Адамыч
        ///Адаша
        ///Аделина
        ///Адя
        ///Аида
        ///Аидка
        ///Акилина
        ///Акилинка
        ///Аксиньюшка
        ///Аксинья
        ///Аксюня
        ///Аксюта
        ///Аксюха
        ///Аксюша
        ///Акся
        ///Акулина
        ///Акулинка
        ///Акуля
        ///Ала
        ///Албин
        ///Албина
        ///Алевтин
        ///Алевтина
        ///Алевтинка
        ///Алевтиныч
        ///Алека
        ///Алексана
        ///Александр
        ///Александра
        ///Александрин
        ///Александрина
        ///Александринка
        ///Александрушка
        ///Александрыч
        ///Ал [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RU_Name {
            get {
                return ResourceManager.GetString("RU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иванов
        ///Смирнов
        ///Кузнецов
        ///Попов
        ///Васильев
        ///Петров
        ///Соколов
        ///Михайлов
        ///Новиков
        ///Федоров
        ///Морозов
        ///Волков
        ///Алексеев
        ///Лебедев
        ///Семенов
        ///Егоров
        ///Павлов
        ///Козлов
        ///Степанов
        ///Николаев
        ///Орлов
        ///Андреев
        ///Макаров
        ///Никитин
        ///Захаров
        ///Зайцев
        ///Соловьев
        ///Борисов
        ///Яковлев
        ///Григорьев
        ///Романов
        ///Воробьев
        ///Сергеев
        ///Кузьмин
        ///Фролов
        ///Александров
        ///Дмитриев
        ///Королев
        ///Гусев
        ///Киселев
        ///Ильин
        ///Максимов
        ///Поляков
        ///Сорокин
        ///Виноградов
        ///Ковалев
        ///Белов
        ///Медведев
        ///Антонов
        ///Тарасов
        ///Жуков
        ///Баранов
        ///Филиппов
        ///Комаров
        ///Давыдов
        ///Беляев
        ///Герасимо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RU_Surname {
            get {
                return ResourceManager.GetString("RU_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на абажур
        ///абаз
        ///абазин
        ///абазинка
        ///абака
        ///аббат
        ///аббатиса
        ///аббатисса
        ///аббатство
        ///аббревиатура
        ///абвер
        ///абверовец
        ///аберрация
        ///абзац
        ///абиогенез
        ///абиссаль
        ///абиссинец
        ///абиссинка
        ///абитуриент
        ///абитуриентка
        ///аболиционизм
        ///аболиционист
        ///аболиционистка
        ///абонемент
        ///абонент
        ///абордаж
        ///аборигенка
        ///аборт
        ///абразив
        ///абразия
        ///абракадабра
        ///абрек
        ///абрикос
        ///абрикотин
        ///абрис
        ///абсент
        ///абсентеизм
        ///абсолют
        ///абсолютизация
        ///абсолютизирование
        ///абсолютизм
        ///абсолютист
        ///абсолютистка
        ///абсолютность
        ///абсорбент
        ///абсорбция
        ///абстрагирование
        ///абст [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RU_Word {
            get {
                return ResourceManager.GetString("RU_Word", resourceCulture);
            }
        }
    }
}
